<div class="page-header mt-3 mb-3">
    <h2>Hello! This is IoTWatcher web dictionary. Type word to find its definition.</h2>
    <?php if ($this->router->getRewriteUri() === "/") { ?>
        <div>To see MindMap of available terms - search for <a href="/mindmap">mindmap</a>. This is semantic graph.</div>
    <div>To start journey through graph - search for <a href="/iotwatcher">iotwatcher</a>.</div>
    <?php } ?>
</div>
<form id="form" action="/" method="post">
    <input type="text" name="word">
    <input type="submit" value="Search">
</form>
<div><?= $message ?></div>
<div class="page-header">
    <h3 class="mt-3"><?= $word; ?></h3>
    <p><?= $output ?></p>
    <?php if($children) {
        echo "<div class='mb-2'>Search for following child terms related to '$word':</div>";
        echo "<ul>";
        foreach ($children as $request) {
            echo "<li><a href='/$request'>$request</a></li>";
        }
        echo "</ul>";
    } ?>
</div>
